// Generated by lsc from approval.ts

method SetToSeq<T>(s: set<T>) returns (res: seq<T>)
  ensures forall x :: x in s <==> x in res
  ensures |res| == |s|
  ensures forall i, j :: 0 <= i < j < |res| ==> res[i] != res[j]
{
  var remaining := s;
  res := [];
  while remaining != {}
    invariant remaining <= s
    invariant forall x :: x in res <==> (x in s && x !in remaining)
    invariant |res| + |remaining| == |s|
    invariant forall i, j :: 0 <= i < j < |res| ==> res[i] != res[j]
    decreases remaining
  {
    var x :| x in remaining;
    res := res + [x];
    remaining := remaining - {x};
  }
}

type UserId = string

type DepartmentId = string

datatype Role = Member | Manager

datatype Directory = Directory(roles: map<string, map<string, Role>>)

datatype Content = Content(title: string, amount: int)

datatype Status = Draft | Pending | Returned(returnedBy: string) | Approved(approvedBy: string) | Rejected(rejectedBy: string)

datatype Request = Request(author: string, department: string, content: Content, status: Status)

datatype Command = Edit(content: Content) | Submit | Approve | Reject | Return

datatype Denial = NotAffiliated | NotAuthor | NotManager | TerminalRequest | WrongState | InvalidContent | NoSuchRequest

datatype Outcome = Success(value: Request) | Failure(denial: Denial)

datatype Event = Event(actor: string, command: Command)

function isAffiliated(dir: Directory, user: UserId, dep: DepartmentId): bool
{
  ((user in dir.roles) && (var i_affiliations_val := dir.roles[user]; (dep in i_affiliations_val)))
}

function isManagerOf(dir: Directory, user: UserId, dep: DepartmentId): bool
{
  ((user in dir.roles) && (var i_affiliations_val := dir.roles[user]; ((dep in i_affiliations_val) && (var i_value := i_affiliations_val[dep]; i_value.Manager?))))
}

lemma isManagerOf_ensures(dir: Directory, user: UserId, dep: DepartmentId)
  ensures (isManagerOf(dir, user, dep) ==> isAffiliated(dir, user, dep))
{
}

function validContent(c: Content): bool
{
  ((c.title != "") && (c.amount >= 0))
}

function isTerminal(s: Status): bool
{
  (s.Approved? || s.Rejected?)
}

function isEditableByAuthor(s: Status): bool
{
  (s.Draft? || s.Returned?)
}

function wellFormed(dir: Directory, r: Request): bool
{
  isAffiliated(dir, r.author, r.department)
}

function canRead(dir: Directory, actor: UserId, r: Request): bool
{
  isAffiliated(dir, actor, r.department)
}

lemma canRead_ensures(dir: Directory, actor: UserId, r: Request)
  ensures (canRead(dir, actor, r) == isAffiliated(dir, actor, r.department))
{
}

function canEdit(dir: Directory, actor: UserId, r: Request): bool
{
  (((actor == r.author) && isEditableByAuthor(r.status)) || (isManagerOf(dir, actor, r.department) && !(isTerminal(r.status))))
}

lemma canEdit_ensures(dir: Directory, actor: UserId, r: Request)
  ensures (canEdit(dir, actor, r) ==> !(isTerminal(r.status)))
  ensures ((actor == r.author) ==> isEditableByAuthor(r.status) ==> canEdit(dir, actor, r))
  ensures (isManagerOf(dir, actor, r.department) ==> r.status.Pending? ==> canEdit(dir, actor, r))
  ensures ((actor != r.author) ==> !(isManagerOf(dir, actor, r.department)) ==> !(canEdit(dir, actor, r)))
{
}

function canSubmit(actor: UserId, r: Request): bool
{
  ((actor == r.author) && isEditableByAuthor(r.status))
}

lemma canSubmit_ensures(actor: UserId, r: Request)
  ensures (canSubmit(actor, r) == ((actor == r.author) && isEditableByAuthor(r.status)))
{
}

function canDecide(dir: Directory, actor: UserId, r: Request): bool
{
  (r.status.Pending? && isManagerOf(dir, actor, r.department))
}

lemma canDecide_ensures(dir: Directory, actor: UserId, r: Request)
  ensures (canDecide(dir, actor, r) == (r.status.Pending? && isManagerOf(dir, actor, r.department)))
{
}

function success(r: Request): Outcome
{
  Success(r)
}

function failure(d: Denial): Outcome
{
  Failure(d)
}

function create(dir: Directory, author: UserId, dep: DepartmentId, content: Content): Outcome
{
  if !(isAffiliated(dir, author, dep)) then
    failure(Denial.NotAffiliated)
  else
    if !(validContent(content)) then
      failure(Denial.InvalidContent)
    else
      success(Request(author, dep, content, Status.Draft))
}

lemma create_ensures(dir: Directory, author: UserId, dep: DepartmentId, content: Content)
  ensures (create(dir, author, dep, content).Success? ==> ((create(dir, author, dep, content).value.author == author) && (create(dir, author, dep, content).value.department == dep)))
  ensures (create(dir, author, dep, content).Success? ==> (create(dir, author, dep, content).value.status.Draft? && wellFormed(dir, create(dir, author, dep, content).value)))
  ensures (create(dir, author, dep, content).Success? ==> validContent(content))
  ensures (isAffiliated(dir, author, dep) ==> validContent(content) ==> create(dir, author, dep, content).Success?)
{
}

function edit(dir: Directory, actor: UserId, r: Request, content: Content): Request
  requires canEdit(dir, actor, r)
{
  r.(content := content)
}

lemma edit_ensures(dir: Directory, actor: UserId, r: Request, content: Content)
  requires canEdit(dir, actor, r)
  ensures (edit(dir, actor, r, content).status == r.status)
  ensures (edit(dir, actor, r, content).author == r.author)
  ensures (edit(dir, actor, r, content).department == r.department)
  ensures (edit(dir, actor, r, content).content == content)
{
}

function submit(actor: UserId, r: Request): Request
  requires canSubmit(actor, r)
{
  r.(status := Status.Pending)
}

lemma submit_ensures(actor: UserId, r: Request)
  requires canSubmit(actor, r)
  ensures submit(actor, r).status.Pending?
  ensures (submit(actor, r).author == r.author)
  ensures (submit(actor, r).department == r.department)
  ensures (submit(actor, r).content == r.content)
{
}

function approve(dir: Directory, actor: UserId, r: Request): Request
  requires canDecide(dir, actor, r)
{
  r.(status := Approved(actor))
}

lemma approve_ensures(dir: Directory, actor: UserId, r: Request)
  requires canDecide(dir, actor, r)
  ensures approve(dir, actor, r).status.Approved?
  ensures (approve(dir, actor, r).status.approvedBy == actor)
  ensures (approve(dir, actor, r).author == r.author)
  ensures (approve(dir, actor, r).department == r.department)
  ensures (approve(dir, actor, r).content == r.content)
{
}

function reject(dir: Directory, actor: UserId, r: Request): Request
  requires canDecide(dir, actor, r)
{
  r.(status := Rejected(actor))
}

lemma reject_ensures(dir: Directory, actor: UserId, r: Request)
  requires canDecide(dir, actor, r)
  ensures reject(dir, actor, r).status.Rejected?
  ensures (reject(dir, actor, r).status.rejectedBy == actor)
  ensures (reject(dir, actor, r).author == r.author)
  ensures (reject(dir, actor, r).department == r.department)
  ensures (reject(dir, actor, r).content == r.content)
{
}

function returnToAuthor(dir: Directory, actor: UserId, r: Request): Request
  requires canDecide(dir, actor, r)
{
  r.(status := Returned(actor))
}

lemma returnToAuthor_ensures(dir: Directory, actor: UserId, r: Request)
  requires canDecide(dir, actor, r)
  ensures returnToAuthor(dir, actor, r).status.Returned?
  ensures (returnToAuthor(dir, actor, r).status.returnedBy == actor)
  ensures (returnToAuthor(dir, actor, r).author == r.author)
  ensures (returnToAuthor(dir, actor, r).department == r.department)
  ensures (returnToAuthor(dir, actor, r).content == r.content)
{
}

function step(dir: Directory, actor: UserId, r: Request, cmd: Command): Outcome
{
  if !(canRead(dir, actor, r)) then
    failure(Denial.NotAffiliated)
  else
    if isTerminal(r.status) then
      failure(Denial.TerminalRequest)
    else
      match cmd {
        case Edit(i_cmd_content) =>
          if canEdit(dir, actor, r) then
            success(edit(dir, actor, r, i_cmd_content))
          else
            failure((if r.status.Pending? then Denial.NotManager else Denial.NotAuthor))
        case Submit =>
          if canSubmit(actor, r) then
            success(submit(actor, r))
          else
            failure((if r.status.Pending? then Denial.WrongState else Denial.NotAuthor))
        case Approve =>
          if canDecide(dir, actor, r) then
            success(approve(dir, actor, r))
          else
            failure((if r.status.Pending? then Denial.NotManager else Denial.WrongState))
        case Reject =>
          if canDecide(dir, actor, r) then
            success(reject(dir, actor, r))
          else
            failure((if r.status.Pending? then Denial.NotManager else Denial.WrongState))
        case Return =>
          if canDecide(dir, actor, r) then
            success(returnToAuthor(dir, actor, r))
          else
            failure((if r.status.Pending? then Denial.NotManager else Denial.WrongState))
      }
}

lemma step_ensures(dir: Directory, actor: UserId, r: Request, cmd: Command)
  ensures (step(dir, actor, r, cmd).Success? ==> canRead(dir, actor, r))
  ensures (isTerminal(r.status) ==> step(dir, actor, r, cmd).Failure?)
  ensures (step(dir, actor, r, cmd).Success? ==> ((step(dir, actor, r, cmd).value.author == r.author) && (step(dir, actor, r, cmd).value.department == r.department)))
  ensures (step(dir, actor, r, cmd).Success? ==> ((cmd.Approve? || cmd.Reject?) || cmd.Return?) ==> canDecide(dir, actor, r))
  ensures (step(dir, actor, r, cmd).Success? ==> cmd.Submit? ==> (canSubmit(actor, r) && step(dir, actor, r, cmd).value.status.Pending?))
  ensures (step(dir, actor, r, cmd).Success? ==> cmd.Edit? ==> (canEdit(dir, actor, r) && (step(dir, actor, r, cmd).value.status == r.status)))
  ensures (canDecide(dir, actor, r) ==> cmd.Approve? ==> (step(dir, actor, r, cmd).Success? && step(dir, actor, r, cmd).value.status.Approved?))
  ensures (canDecide(dir, actor, r) ==> cmd.Reject? ==> (step(dir, actor, r, cmd).Success? && step(dir, actor, r, cmd).value.status.Rejected?))
  ensures (canDecide(dir, actor, r) ==> cmd.Return? ==> (step(dir, actor, r, cmd).Success? && step(dir, actor, r, cmd).value.status.Returned?))
  ensures (step(dir, actor, r, cmd).Success? ==> (step(dir, actor, r, cmd).value.status != r.status) ==> (!(isTerminal(r.status)) && (if r.status.Pending? then (isTerminal(step(dir, actor, r, cmd).value.status) || step(dir, actor, r, cmd).value.status.Returned?) else step(dir, actor, r, cmd).value.status.Pending?)))
{
}

function hasManager(dir: Directory, dep: DepartmentId): bool
{
  exists user <- dir.roles.Keys :: isManagerOf(dir, user, dep)
}
by method {
  var i_user_keys := SetToSeq(dir.roles.Keys);
  var i_user_idx := 0;
  while i_user_idx < |i_user_keys|
    invariant (i_user_idx <= |i_user_keys|)
    invariant forall j :: 0 <= j < i_user_idx ==> !isManagerOf(dir, i_user_keys[j], dep)
  {
    var user := i_user_keys[i_user_idx];
    var affiliations := dir.roles[user];
    if ((dep in affiliations) && (var i_value := affiliations[dep]; i_value.Manager?)) {
      return true;
    }
    i_user_idx := i_user_idx + 1;
  }
  return false;
}

function departmentsHaveManagers(dir: Directory): bool
{
  forall user <- dir.roles.Keys, dep <- dir.roles[user].Keys :: hasManager(dir, dep)
}
by method {
  var i_user_keys := SetToSeq(dir.roles.Keys);
  var i_user_idx := 0;
  while i_user_idx < |i_user_keys|
    invariant (i_user_idx <= |i_user_keys|)
    invariant forall j :: 0 <= j < i_user_idx ==> forall d <- dir.roles[i_user_keys[j]].Keys :: hasManager(dir, d)
  {
    var user := i_user_keys[i_user_idx];
    var affiliations := dir.roles[user];
    var i_dep_keys := SetToSeq(affiliations.Keys);
    var i_dep_idx := 0;
    while i_dep_idx < |i_dep_keys|
      invariant (i_dep_idx <= |i_dep_keys|)
      invariant forall j :: 0 <= j < i_dep_idx ==> hasManager(dir, i_dep_keys[j])
    {
      var dep := i_dep_keys[i_dep_idx];
      var role := affiliations[dep];
      var i_t0 := hasManager(dir, dep);
      if !(i_t0) {
        return false;
      }
      i_dep_idx := i_dep_idx + 1;
    }
    i_user_idx := i_user_idx + 1;
  }
  return true;
}

method run(dir: Directory, r: Request, events: seq<Event>) returns (res: Request)
  ensures (res.author == r.author)
  ensures (res.department == r.department)
  ensures (wellFormed(dir, r) ==> wellFormed(dir, res))
  ensures (isTerminal(r.status) ==> (res == r))
{
  var current := r;
  var i := 0;
  while (i < |events|)
    invariant (0 <= i)
    invariant (i <= |events|)
    invariant (current.author == r.author)
    invariant (current.department == r.department)
    invariant (isTerminal(r.status) ==> (current == r))
  {
    var i_t1 := step(dir, events[i].actor, current, events[i].command);
    var outcome := i_t1;
    match outcome {
      case Success(i_outcome_value) =>
        current := i_outcome_value;
      case Failure(i_outcome_denial) =>

    }
    i := (i + 1);
  }
  return current;
}

class Workflow {
  var directory: Directory
  var requests: map<int, Request>
  var nextId: int

  method open(author: UserId, dep: DepartmentId, content: Content) returns (res: Outcome)
    requires forall id: int :: ((id in this.requests) ==> wellFormed(this.directory, this.requests[id]))
    ensures forall id: int :: ((id in this.requests) ==> wellFormed(this.directory, this.requests[id]))
    ensures (res.Success? ==> (((this.nextId - 1) in this.requests) && (this.requests[(this.nextId - 1)] == res.value)))
    ensures (res.Success? ==> (((res.value.author == author) && (res.value.department == dep)) && res.value.status.Draft?))
    modifies this
  {
    var i_t2 := create(this.directory, author, dep, content);
    var outcome := i_t2;
    match outcome {
      case Success(i_outcome_value) =>
        var stored := this.requests;
        stored := stored[this.nextId := i_outcome_value];
        this.requests := stored;
        this.nextId := (this.nextId + 1);
      case Failure(i_outcome_denial) =>

    }
    return outcome;
  }
  method apply(actor: UserId, id: int, cmd: Command) returns (res: Outcome)
    requires forall k: int :: ((k in this.requests) ==> wellFormed(this.directory, this.requests[k]))
    ensures forall k: int :: ((k in this.requests) ==> wellFormed(this.directory, this.requests[k]))
    ensures (res.Success? ==> ((id in this.requests) && (this.requests[id] == res.value)))
    modifies this
  {
    if (id in this.requests) {
      var i_current_val := this.requests[id];
      var i_t3 := step(this.directory, actor, i_current_val, cmd);
      var outcome := i_t3;
      match outcome {
        case Success(i_outcome_value) =>
          var stored := this.requests;
          stored := stored[id := i_outcome_value];
          this.requests := stored;
        case Failure(i_outcome_denial) =>

      }
      return outcome;
    } else {
      var i_t4 := failure(Denial.NoSuchRequest);
      return i_t4;
    }
  }
}

// ---------------------------------------------------------------------------
// Proof additions (not generated from approval.ts): the theorems of ../spec.md
// stated over the generated definitions. approval.ts states the one-step
// facts as `ensures`; these lemmas name P1-P3 explicitly and lift them to
// requests held by a `Workflow`.
// ---------------------------------------------------------------------------

// P1: a successful decision is always taken by a Manager of the *target*
// department. Being a Manager elsewhere gives no authority here.
lemma NoAuthorityLeakAcrossDepartments(dir: Directory, actor: UserId, r: Request, cmd: Command, other: DepartmentId)
  requires cmd.Approve? || cmd.Reject? || cmd.Return?
  requires step(dir, actor, r, cmd).Success?
  ensures isManagerOf(dir, actor, r.department)
  ensures other != r.department ==> !isManagerOf(dir, actor, other) || isManagerOf(dir, actor, r.department)
{
}

// spec.md 4 D: nothing forbids the author approving their own request when
// the author is also a Manager of the target department.
lemma SelfApprovalIsPermitted(dir: Directory, author: UserId, r: Request)
  requires r.author == author && r.status.Pending?
  requires isManagerOf(dir, author, r.department)
  ensures step(dir, author, r, Approve).Success?
{
}

// P2: an Approved or Rejected request accepts no command at all, and stays
// exactly as it is along any trace (the postcondition of `run`).
lemma TerminalRequestsRejectEveryCommand(dir: Directory, actor: UserId, r: Request, cmd: Command)
  requires isTerminal(r.status)
  ensures step(dir, actor, r, cmd).Failure?
  ensures step(dir, actor, r, cmd).denial == TerminalRequest || step(dir, actor, r, cmd).denial == NotAffiliated
{
}

// P3: in a directory where every department has a Manager, every well-formed
// Pending request has someone entitled to decide it ...
lemma EveryPendingRequestHasADecider(dir: Directory, r: Request)
  requires departmentsHaveManagers(dir)
  requires wellFormed(dir, r) && r.status.Pending?
  ensures exists decider: UserId :: canDecide(dir, decider, r)
{
  assert r.author in dir.roles.Keys && r.department in dir.roles[r.author].Keys;
  assert hasManager(dir, r.department);
  var m :| m in dir.roles.Keys && isManagerOf(dir, m, r.department);
  assert canDecide(dir, m, r);
}

// ... and that person can actually bring it to a terminal state.
lemma PendingRequestsCanBeDecided(dir: Directory, r: Request)
  requires departmentsHaveManagers(dir)
  requires wellFormed(dir, r) && r.status.Pending?
  ensures exists e: Event :: step(dir, e.actor, r, e.command).Success? && isTerminal(step(dir, e.actor, r, e.command).value.status)
{
  EveryPendingRequestHasADecider(dir, r);
  var decider :| canDecide(dir, decider, r);
  var e := Event(decider, Approve);
  assert step(dir, e.actor, r, e.command).Success? && isTerminal(step(dir, e.actor, r, e.command).value.status);
}

// P3 for a running service: the `requires`/`ensures` of `Workflow.open` and
// `Workflow.apply` keep every stored request well formed, so no Pending
// request in the store is ever orphaned.
lemma WorkflowHasNoOrphanedRequests(w: Workflow)
  requires departmentsHaveManagers(w.directory)
  requires forall id: int :: id in w.requests ==> wellFormed(w.directory, w.requests[id])
  ensures forall id: int :: id in w.requests && w.requests[id].status.Pending? ==> exists decider: UserId :: canDecide(w.directory, decider, w.requests[id])
{
  forall id: int | id in w.requests && w.requests[id].status.Pending?
    ensures exists decider: UserId :: canDecide(w.directory, decider, w.requests[id])
  {
    EveryPendingRequestHasADecider(w.directory, w.requests[id]);
  }
}
